In [26]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.datasets import load_iris

In [27]:
data = load_iris()

In [30]:
X, y = data['data'], data['target']
X.shape, y.shape

((150, 4), (150,))

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state = 10, test_size = 0.2)

In [53]:
X_train.shape

(120, 4)

In [54]:
X_test.shape

(30, 4)

In [55]:
Y_train.shape

(120,)

In [56]:
Y_test.shape

(30,)

In [67]:
X_test[1]

array([6.4, 2.7, 5.3, 1.9])

In [68]:
Y_test[1]

2

# Logistic Regression

In [59]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [60]:
classifier = model.fit(X_train, Y_train)

In [61]:
Predicted = model.predict(X_test)

In [62]:
Predicted

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(Y_test, Predicted)

array([[10,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  7]])

In [64]:
accuracy_score(Y_test, Predicted)

1.0

# K-NN

In [73]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)
baatu =model.fit(X_train, Y_train)

In [77]:
predict = baatu.predict(X_test)
predict

array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [79]:
print(confusion_matrix(Y_test, predict))
print(accuracy_score(Y_test, predict))


[[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]
0.9666666666666667


# SVM

In [108]:
from sklearn.svm import SVC
model = SVC(kernel="linear", C = 0.01)

In [109]:
tg = model.fit(X_train, Y_train)

In [110]:
predicty = model.predict(X_test)
predicty

array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 2, 2])

In [111]:
accuracy_score(Y_test, predicty)

0.9333333333333333

In [112]:
confusion_matrix(Y_test, predicty)

array([[10,  0,  0],
       [ 0, 11,  2],
       [ 0,  0,  7]])

In [69]:
import pickle 
  
# Save the trained model as a pickle string. 
saved_model = pickle.dumps(model) 
  
# Load the pickled model 
knn_from_pickle = pickle.loads(saved_model) 
  
# Use the loaded pickled model to make predictions 
knn_from_pickle.predict(X_test) 

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [71]:
#from sklearn.externals import joblib 
import joblib  
# Save the model as a pickle in a file 
joblib.dump(model, 'baatu.pkl') 
  
# Load the model from the file 
knn_from_joblib = joblib.load('baatu.pkl')  
  
# Use the loaded model to make predictions 
knn_from_joblib.predict(X_test) 

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])