In [27]:
import numpy as np
import pandas as pd
data = pd.read_csv("/home/baatu-tech/Downloads/iris.data")
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [32]:
data.columns = ['sepal_lenth', 'sepal_width', 'petal_length', 'petal_width','result']

In [33]:
data.head()

sepal_lenth  sepal_width  petal_length  petal_width       result
0          4.9          3.0           1.4          0.2  Iris-setosa
1          4.7          3.2           1.3          0.2  Iris-setosa
2          4.6          3.1           1.5          0.2  Iris-setosa
3          5.0          3.6           1.4          0.2  Iris-setosa
4          5.4          3.9           1.7          0.4  Iris-setosa

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_lenth   149 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  149 non-null    float64
 3   petal_width   149 non-null    float64
 4   result        149 non-null    object 
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [35]:
data.describe()

sepal_lenth  sepal_width  petal_length  petal_width
count   149.000000   149.000000    149.000000   149.000000
mean      5.848322     3.051007      3.774497     1.205369
std       0.828594     0.433499      1.759651     0.761292
min       4.300000     2.000000      1.000000     0.100000
25%       5.100000     2.800000      1.600000     0.300000
50%       5.800000     3.000000      4.400000     1.300000
75%       6.400000     3.300000      5.100000     1.800000
max       7.900000     4.400000      6.900000     2.500000

In [39]:
data.isnull().sum()

sepal_lenth     0
sepal_width     0
petal_length    0
petal_width     0
result          0
dtype: int64

In [40]:
data.duplicated().sum()

3

In [44]:
data.drop_duplicates(inplace=True)

In [45]:
data.shape

(146, 5)

In [46]:
data.head()

sepal_lenth  sepal_width  petal_length  petal_width       result
0          4.9          3.0           1.4          0.2  Iris-setosa
1          4.7          3.2           1.3          0.2  Iris-setosa
2          4.6          3.1           1.5          0.2  Iris-setosa
3          5.0          3.6           1.4          0.2  Iris-setosa
4          5.4          3.9           1.7          0.4  Iris-setosa

In [63]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [53]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X=data.iloc[:,0:3]
Y=data.iloc[:,-1]

In [64]:
le.fit_transform(Y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [89]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=2)

In [90]:
model=LogisticRegression()

In [91]:
model.fit(X_train,Y_train)

LogisticRegression()

In [92]:
prediction=model.predict(X_test)

In [93]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [94]:
confusion_matrix(Y_test,prediction)

array([[11,  0,  0],
       [ 0, 11,  0],
       [ 0,  1,  7]])

In [95]:
accuracy_score(Y_test,prediction)

0.9666666666666667

# K-NN Classifier

In [96]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier()
knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [100]:
prediction1 = knn.predict(X_test)

In [101]:
confusion_matrix(Y_test,prediction1)

array([[11,  0,  0],
       [ 0, 11,  0],
       [ 0,  0,  8]])

In [102]:
accuracy_score(Y_test,prediction1)

1.0

# SVC

In [113]:
from sklearn.svm import SVC
model1 = SVC()
X_train,Y_train,X_test, Y_test = train_test_split(X,Y, test_size=0.2, random_state=10)

In [105]:
model1.fit(X_train,Y_train)

SVC()

In [106]:
X_train.shape

(116, 3)

In [107]:
X_test.shape

(30, 3)

In [108]:
prediction2 = model1.predict(X_test)

In [109]:
confusion_matrix(Y_test,prediction2)

array([[11,  0,  0],
       [ 0, 11,  0],
       [ 0,  1,  7]])

In [111]:
accuracy_score(Y_test,prediction2)

0.9666666666666667