In [9]:
import numpy as np
from sklearn.decomposition import PCA
import pandas as pd
import matplotlib.pyplot as plt

In [20]:
health ={'Ethnicity':['white','Asian','african','white','asian'],
                 'Height':[180,190,120,145,185],
                 'weight': [45,65,42,53,65],
                 'survive':['yes','No','yes','No','No']}
#print(health)
#type(health)
df = pd.DataFrame.from_dict(health)
print(df)

  Ethnicity  Height  weight survive
0     white     180      45     yes
1     Asian     190      65      No
2   african     120      42     yes
3     white     145      53      No
4     asian     185      65      No


In [21]:

#df = pd.read_csv ('Health.csv')

X = df.iloc [:,0:3].values  # X is independent variable
y = df.iloc [:,3].values   #dependent variable

In [25]:
from sklearn.preprocessing import LabelEncoder
X_labelencoder = LabelEncoder()
X[:, 0] = X_labelencoder.fit_transform(X[:, 0])
#print (X)

# for y
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
#print (y)

In [26]:


print("before PCA: ")
print(X)
pc = PCA(n_components=2)
pc.fit(X)

X_pca = pc.transform(X)
print("After doing PCA")
print(X_pca)



before PCA: 
[[3 180 45]
 [0 190 65]
 [1 120 42]
 [3 145 53]
 [2 185 65]]
After doing PCA
[[-13.13330623  12.87939888]
 [-27.96421532  -4.04036023]
 [ 45.60273667   0.1733681 ]
 [ 18.62004313  -3.83652056]
 [-23.12525825  -5.17588618]]


In [28]:
print("original shape:   ", X.shape)  # (9,3)
print("transformed shape:", X_pca.shape) #(9,2) when n_components =2


original shape:    (5, 3)
transformed shape: (5, 2)


In [29]:
print(pc.explained_variance_ratio_)   # # 93% data belongs to first axis and 5% data belongs to the second axis and remaining belongs to others


[0.94469558 0.05398142]


In [ ]:
df = pd.DataFrame(X_pca,columns = ['PCA1','PCA2'])
print(df)
#print(df.iloc[:,0